version: "3.8"
services: 
  web: 
    build: . 
    ports: 
    - "8000:8000"
    env_file: .env
    depends_on: 
    - db
  
  db: 
    image: postgres:15
    environment: 
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes: 
    - pgdata:/var/lib/postgresql/data

volumes: 
  pgdata:

