apiVersion: apps/v1
kind: Deployment
metadata: 
  name: fastapi-deployment
spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: fastapi
  template: 
    metadata: 
      labels:
        app: fastapi
    spec: 
      containers: 
      - name: fastapi-container
        image: mukul0412/fastapi-k8s-app:latest
        ports: 
        - containerPort: 8000
